import { RepoMetadata, RepoTreeItem } from '../types';

export interface DemoRepoData {
  metadata: RepoMetadata;
  tree: RepoTreeItem[];
  readme: string;
  sampleFiles: Record<string, string>;
}

export const DEMO_REPOSITORIES: Record<string, DemoRepoData> = {
  'coderamp-labs/gitingest': {
    metadata: {
      owner: 'coderamp-labs',
      name: 'gitingest',
      fullName: 'coderamp-labs/gitingest',
      description: 'Turn any Git repository into a prompt-friendly text ingest for LLMs.',
      stars: 18400,
      forks: 1420,
      openIssues: 42,
      defaultBranch: 'main',
      language: 'Python',
      license: 'MIT',
      topics: ['llm', 'git', 'prompt-engineering', 'context-window', 'fastapi'],
      htmlUrl: 'https://github.com/coderamp-labs/gitingest',
      updatedAt: '2026-03-28T14:20:00Z',
      sizeKb: 3820,
    },
    readme: `# Gitingest\n\nTurn any Git repository into a prompt-friendly text ingest for LLMs.\n\n## Features\n- Easy code context: Get a text digest from a Git repository URL or a directory\n- Smart Formatting: Optimized output format for LLM prompts\n- Statistics about file/dir structure, size, and token counts\n- CLI tool & Python package\n\n## Usage\nReplace "hub" with "ingest" in any GitHub URL to access the corresponding digest.`,
    sampleFiles: {
      'src/gitingest/entrypoint.py': 'async def ingest_async(source: str, max_file_size: int = 10_000_000, include_patterns = None, exclude_patterns = None):\n    # Clone and analyze repo\n    pass',
      'src/gitingest/query_parser.py': 'async def parse_remote_repo(source: str, token: str | None = None) -> IngestionQuery:\n    # Normalizes GitHub URL, extracts branch and subpath\n    pass',
      'src/server/main.py': 'from fastapi import FastAPI\napp = FastAPI(title="Gitingest")\n@app.get("/{user}/{repo}")\nasync def ingest_page(user: str, repo: str):\n    return templates.TemplateResponse("git.jinja")',
    },
    tree: [
      { path: 'src', mode: '040000', type: 'tree', sha: 't1' },
      { path: 'src/gitingest', mode: '040000', type: 'tree', sha: 't2' },
      { path: 'src/gitingest/__init__.py', mode: '100644', type: 'blob', sha: 'b1', size: 167 },
      { path: 'src/gitingest/entrypoint.py', mode: '100644', type: 'blob', sha: 'b2', size: 13418 },
      { path: 'src/gitingest/ingestion.py', mode: '100644', type: 'blob', sha: 'b3', size: 11114 },
      { path: 'src/gitingest/clone.py', mode: '100644', type: 'blob', sha: 'b4', size: 6409 },
      { path: 'src/gitingest/query_parser.py', mode: '100644', type: 'blob', sha: 'b5', size: 6354 },
      { path: 'src/gitingest/output_formatter.py', mode: '100644', type: 'blob', sha: 'b6', size: 7141 },
      { path: 'src/server', mode: '040000', type: 'tree', sha: 't3' },
      { path: 'src/server/main.py', mode: '100644', type: 'blob', sha: 'b7', size: 7626 },
      { path: 'src/server/query_processor.py', mode: '100644', type: 'blob', sha: 'b8', size: 14821 },
      { path: 'src/server/templates', mode: '040000', type: 'tree', sha: 't4' },
      { path: 'src/server/templates/base.jinja', mode: '100644', type: 'blob', sha: 'b9', size: 3462 },
      { path: 'src/server/templates/components/git_form.jinja', mode: '100644', type: 'blob', sha: 'b10', size: 12473 },
      { path: 'src/server/templates/components/result.jinja', mode: '100644', type: 'blob', sha: 'b11', size: 8241 },
      { path: 'README.md', mode: '100644', type: 'blob', sha: 'b12', size: 14882 },
      { path: 'pyproject.toml', mode: '100644', type: 'blob', sha: 'b13', size: 3705 },
      { path: 'Dockerfile', mode: '100644', type: 'blob', sha: 'b14', size: 1528 },
    ],
  },
  'ahmedkhaleel2004/gitdiagram': {
    metadata: {
      owner: 'ahmedkhaleel2004',
      name: 'gitdiagram',
      fullName: 'ahmedkhaleel2004/gitdiagram',
      description: 'Turn any GitHub repository into an interactive architecture diagram or narrated video.',
      stars: 12800,
      forks: 980,
      openIssues: 28,
      defaultBranch: 'main',
      language: 'TypeScript',
      license: 'MIT',
      topics: ['nextjs', 'mermaid', 'diagram', 'architecture', 'ai-agent', 'mcp'],
      htmlUrl: 'https://github.com/ahmedkhaleel2004/gitdiagram',
      updatedAt: '2026-04-01T11:00:00Z',
      sizeKb: 5200,
    },
    readme: `# GitDiagram\n\nVisualize any codebase: turn any public or private GitHub repository into an interactive architecture diagram, or watch it explained in a one-minute narrated video.\n\nReplace "hub" with "diagram" in any GitHub repository URL.`,
    sampleFiles: {
      'src/server/generate/graph.ts': 'export function planArchitectureGraph(context: RepoContext): GraphSchema {\n  // Extracts subsystems, nodes, edges, and produces Mermaid flowchart\n}',
      'src/features/diagram/mermaid-config.ts': 'export const MERMAID_THEME = { theme: "neutral", flowchart: { curve: "basis" } };',
      'src/app/page.tsx': 'export default function HomePage() { return <MainCard /> }',
    },
    tree: [
      { path: 'src', mode: '040000', type: 'tree', sha: 't1' },
      { path: 'src/app', mode: '040000', type: 'tree', sha: 't2' },
      { path: 'src/app/page.tsx', mode: '100644', type: 'blob', sha: 'b1', size: 5254 },
      { path: 'src/app/[username]/[repo]/page.tsx', mode: '100644', type: 'blob', sha: 'b2', size: 4890 },
      { path: 'src/components', mode: '040000', type: 'tree', sha: 't3' },
      { path: 'src/components/main-card.tsx', mode: '100644', type: 'blob', sha: 'b3', size: 7269 },
      { path: 'src/components/hero.tsx', mode: '100644', type: 'blob', sha: 'b4', size: 3120 },
      { path: 'src/features', mode: '040000', type: 'tree', sha: 't4' },
      { path: 'src/features/diagram/api.ts', mode: '100644', type: 'blob', sha: 'b5', size: 5278 },
      { path: 'src/features/diagram/mermaid-config.ts', mode: '100644', type: 'blob', sha: 'b6', size: 2664 },
      { path: 'src/features/diagram/graph.ts', mode: '100644', type: 'blob', sha: 'b7', size: 4928 },
      { path: 'src/server', mode: '040000', type: 'tree', sha: 't5' },
      { path: 'src/server/generate/graph.ts', mode: '100644', type: 'blob', sha: 'b8', size: 15274 },
      { path: 'src/server/generate/prompts.ts', mode: '100644', type: 'blob', sha: 'b9', size: 13625 },
      { path: 'src/server/generate/mermaid-validator.ts', mode: '100644', type: 'blob', sha: 'b10', size: 9242 },
      { path: 'README.md', mode: '100644', type: 'blob', sha: 'b11', size: 5983 },
      { path: 'package.json', mode: '100644', type: 'blob', sha: 'b12', size: 5141 },
    ],
  },
  'reverse-codes/gitreverse': {
    metadata: {
      owner: 'reverse-codes',
      name: 'gitreverse',
      fullName: 'reverse-codes/gitreverse',
      description: 'Reverse engineer any GitHub repository or website into a plain-language coding agent prompt.',
      stars: 4850,
      forks: 310,
      openIssues: 12,
      defaultBranch: 'main',
      language: 'TypeScript',
      license: 'MIT',
      topics: ['cursor', 'claude-code', 'vibe-coding', 'prompt-engineering', 'nextjs'],
      htmlUrl: 'https://github.com/reverse-codes/gitreverse',
      updatedAt: '2026-03-15T09:30:00Z',
      sizeKb: 2100,
    },
    readme: `# GitReverse\n\nTurn a public GitHub repository into a single synthetic user prompt that someone might paste into Cursor, Claude Code, Codex, etc. to vibe code the project from scratch.\n\nThe app pulls repo metadata, a root file tree, and the README, then uses an LLM to produce one short, conversational prompt.`,
    sampleFiles: {
      'lib/system-prompt.ts': 'export const SYSTEM_PROMPT = `You are an expert at inferring how people actually prompt modern coding agents...`;',
      'app/api/reverse-prompt/route.ts': 'export async function POST(req: NextRequest) { /* generate synthetic prompt */ }',
    },
    tree: [
      { path: 'app', mode: '040000', type: 'tree', sha: 't1' },
      { path: 'app/page.tsx', mode: '100644', type: 'blob', sha: 'b1', size: 1373 },
      { path: 'app/globals.css', mode: '100644', type: 'blob', sha: 'b2', size: 492 },
      { path: 'app/api/reverse-prompt/route.ts', mode: '100644', type: 'blob', sha: 'b3', size: 17516 },
      { path: 'components', mode: '040000', type: 'tree', sha: 't2' },
      { path: 'components/reverse-prompt-home.tsx', mode: '100644', type: 'blob', sha: 'b4', size: 25329 },
      { path: 'components/navbar.tsx', mode: '100644', type: 'blob', sha: 'b5', size: 3410 },
      { path: 'lib', mode: '040000', type: 'tree', sha: 't3' },
      { path: 'lib/system-prompt.ts', mode: '100644', type: 'blob', sha: 'b6', size: 2281 },
      { path: 'lib/github-client.ts', mode: '100644', type: 'blob', sha: 'b7', size: 4120 },
      { path: 'lib/file-tree-formatter.ts', mode: '100644', type: 'blob', sha: 'b8', size: 3200 },
      { path: 'README.md', mode: '100644', type: 'blob', sha: 'b9', size: 4081 },
      { path: 'package.json', mode: '100644', type: 'blob', sha: 'b10', size: 936 },
    ],
  },
  'fastapi/fastapi': {
    metadata: {
      owner: 'fastapi',
      name: 'fastapi',
      fullName: 'fastapi/fastapi',
      description: 'FastAPI framework, high performance, easy to learn, fast to code, ready for production',
      stars: 82000,
      forks: 7100,
      openIssues: 195,
      defaultBranch: 'master',
      language: 'Python',
      license: 'MIT',
      topics: ['python', 'asgi', 'openapi', 'pydantic', 'async', 'api'],
      htmlUrl: 'https://github.com/fastapi/fastapi',
      updatedAt: '2026-04-02T18:00:00Z',
      sizeKb: 14500,
    },
    readme: `# FastAPI\n\nFastAPI is a modern, fast (high-performance), web framework for building APIs with Python based on standard Python type hints.\n\nKey features: Fast to code, Fewer bugs, Intuitive, Easy, Short, Robust, Standards-based.`,
    sampleFiles: {
      'fastapi/applications.py': 'class FastAPI(Starlette):\n    def __init__(self, debug: bool = False, routes: list = None):\n        super().__init__()',
      'fastapi/routing.py': 'class APIRoute(routing.Route):\n    def __init__(self, path: str, endpoint: Callable):\n        pass',
    },
    tree: [
      { path: 'fastapi', mode: '040000', type: 'tree', sha: 't1' },
      { path: 'fastapi/applications.py', mode: '100644', type: 'blob', sha: 'b1', size: 21300 },
      { path: 'fastapi/routing.py', mode: '100644', type: 'blob', sha: 'b2', size: 31200 },
      { path: 'fastapi/params.py', mode: '100644', type: 'blob', sha: 'b3', size: 14500 },
      { path: 'fastapi/dependencies/utils.py', mode: '100644', type: 'blob', sha: 'b4', size: 18200 },
      { path: 'fastapi/openapi/utils.py', mode: '100644', type: 'blob', sha: 'b5', size: 19800 },
      { path: 'fastapi/encoders.py', mode: '100644', type: 'blob', sha: 'b6', size: 8400 },
      { path: 'fastapi/exceptions.py', mode: '100644', type: 'blob', sha: 'b7', size: 4500 },
      { path: 'README.md', mode: '100644', type: 'blob', sha: 'b8', size: 22000 },
      { path: 'pyproject.toml', mode: '100644', type: 'blob', sha: 'b9', size: 5400 },
    ],
  },
  'shadcn-ui/ui': {
    metadata: {
      owner: 'shadcn-ui',
      name: 'ui',
      fullName: 'shadcn-ui/ui',
      description: 'Beautifully designed components that you can copy and paste into your apps. Accessible. Customizable. Open Source.',
      stars: 84500,
      forks: 6400,
      openIssues: 120,
      defaultBranch: 'main',
      language: 'TypeScript',
      license: 'MIT',
      topics: ['react', 'tailwindcss', 'radix-ui', 'components', 'ui'],
      htmlUrl: 'https://github.com/shadcn-ui/ui',
      updatedAt: '2026-04-03T16:20:00Z',
      sizeKb: 18200,
    },
    readme: `# shadcn/ui\n\nAccessible and customizable components that you can copy and paste into your apps. Free. Open Source. Use this to build your own component library.`,
    sampleFiles: {
      'packages/cli/src/index.ts': '#!/usr/bin/env node\nimport { Command } from "commander";',
      'apps/www/components/ui/button.tsx': 'export const Button = React.forwardRef(...)',
    },
    tree: [
      { path: 'packages', mode: '040000', type: 'tree', sha: 't1' },
      { path: 'packages/cli/src/index.ts', mode: '100644', type: 'blob', sha: 'b1', size: 5200 },
      { path: 'packages/cli/src/commands/add.ts', mode: '100644', type: 'blob', sha: 'b2', size: 8400 },
      { path: 'packages/cli/src/commands/init.ts', mode: '100644', type: 'blob', sha: 'b3', size: 9100 },
      { path: 'apps/www/components/ui/button.tsx', mode: '100644', type: 'blob', sha: 'b4', size: 3100 },
      { path: 'apps/www/components/ui/dialog.tsx', mode: '100644', type: 'blob', sha: 'b5', size: 4500 },
      { path: 'README.md', mode: '100644', type: 'blob', sha: 'b6', size: 12000 },
      { path: 'package.json', mode: '100644', type: 'blob', sha: 'b7', size: 3100 },
    ],
  },
};
