import { RepoMetadata, RepoTreeItem } from '../types';

export interface DemoRepoData {
  metadata: RepoMetadata;
  tree: RepoTreeItem[];
  readme: string;
  sampleFiles: Record<string, string>;
}

export const DEMO_REPOSITORIES: Record<string, DemoRepoData> = {
  'yashinrush/rushclaw.ai': {
    metadata: {
      owner: 'yashinrush',
      name: 'RushClaw.AI',
      fullName: 'yashinrush/RushClaw.AI',
      description: 'Autonomous Agentic Coding Assistant & Multi-Mode CLI built with Bun & TypeScript. Transform natural language prompts into safely staged, approval-gated codebase changes with CLI and Telegram Bot control.',
      stars: 142,
      forks: 28,
      openIssues: 2,
      defaultBranch: 'main',
      language: 'TypeScript',
      license: 'MIT',
      topics: ['agent', 'cli', 'telegram-bot', 'gemini', 'bun', 'typescript', 'ai-coding-assistant'],
      htmlUrl: 'https://github.com/yashinrush/RushClaw.AI',
      updatedAt: '2026-09-25T15:37:00Z',
      sizeKb: 420,
    },
    readme: `# RushClaw.AI 🦅\n\n**Autonomous Agentic Coding Assistant & Multi-Mode CLI built with Bun & TypeScript.**\nTransform natural language prompts into safely staged, approval-gated codebase changes with CLI and Telegram Bot control.\n\n## Overview\nRushClaw.AI is an intelligent, high-performance developer tool that executes complex software development tasks autonomously while keeping you firmly in control. Built from the ground up using Bun and the Vercel AI SDK, RushClaw supports Google Gemini (Google AI Studio) and OpenRouter models, web research via Firecrawl, git-style diff previews, and remote operation via a Telegram Bot.\n\nEvery single codebase mutation is staged in-memory, visualized with colored diffs, and requires explicit user approval before touching your disk.\n\n## Operating Modes\n1. **Agent Mode**: Loops through multi-step reasoning, file inspection, directory tree analysis, and code synthesis.\n2. **Deep Plan Mode**: Researches your goal, analyzes current skills and dependencies, queries live web sources, drafts a plan, and lets you select which steps to execute.\n3. **Interactive Ask Mode**: Deep read-only Q&A about code semantics, architecture, or tech stacks with optional Markdown report exporting.\n4. **Telegram Bot Mode**: Run Agent, Plan, and Ask modes remotely via Telegram with inline buttons for step execution, diff previews, and change approvals.`,
    sampleFiles: {
      'index.ts': 'import { Command } from "commander";\nimport { wakeup } from "./tui/wakeup";\nconst program = new Command();\nprogram.command("wakeup").action(wakeup);',
      'ai/ai.config.ts': 'import { createGoogleGenerativeAI } from "@ai-sdk/google";\nimport { createOpenRouter } from "@openrouter/ai-sdk-provider";\nexport const getModel = () => { /* returns configured model */ };',
      'modes/cli.ts': 'import * as p from "@clack/prompts";\nexport async function selectMode() { return await p.select({ message: "Select mode:", options: [] }); }',
      'modes/agent/orchestrator.ts': 'export async function runAgentMode(task: string) {\n  // Multi-step reasoning loop with tool execution and staging\n}',
      'modes/agent/tool-executor.ts': 'export class ToolExecutor {\n  private stagedChanges = new Map();\n  stageFile(path: string, content: string) { this.stagedChanges.set(path, content); }\n}',
      'modes/agent/approval.ts': 'export async function requestApproval(changes: any) {\n  // Render diff and prompt: Apply changes? [Yes / No]\n}',
      'modes/plan/planner.ts': 'export async function generatePlan(goal: string) {\n  // Generates structured 1-15 step plan with difficulty ratings\n}',
      'modes/telegram/index.ts': 'import { Telegraf } from "telegraf";\nexport function startTelegramBot(token: string) { /* remote bot runner */ }',
      'tui/wakeup.ts': 'export async function wakeup() {\n  // Dual-pass ASCII banner & interactive launcher\n}',
      'tui/terminal-md.ts': 'import { marked } from "marked";\nexport function renderMarkdown(content: string) { return marked(content); }',
    },
    tree: [
      { path: 'index.ts', mode: '100644', type: 'blob', sha: 'rc1', size: 424 },
      { path: 'package.json', mode: '100644', type: 'blob', sha: 'rc2', size: 725 },
      { path: 'README.md', mode: '100644', type: 'blob', sha: 'rc3', size: 11537 },
      { path: 'tsconfig.json', mode: '100644', type: 'blob', sha: 'rc4', size: 755 },
      { path: 'ai', mode: '040000', type: 'tree', sha: 'rc5' },
      { path: 'ai/ai.config.ts', mode: '100644', type: 'blob', sha: 'rc6', size: 759 },
      { path: 'ai/index.ts', mode: '100644', type: 'blob', sha: 'rc7', size: 45 },
      { path: 'modes', mode: '040000', type: 'tree', sha: 'rc8' },
      { path: 'modes/cli.ts', mode: '100644', type: 'blob', sha: 'rc9', size: 1204 },
      { path: 'modes/agent', mode: '040000', type: 'tree', sha: 'rc10' },
      { path: 'modes/agent/action-tracker.ts', mode: '100644', type: 'blob', sha: 'rc11', size: 1237 },
      { path: 'modes/agent/agent-tools.ts', mode: '100644', type: 'blob', sha: 'rc12', size: 4265 },
      { path: 'modes/agent/approval.ts', mode: '100644', type: 'blob', sha: 'rc13', size: 4166 },
      { path: 'modes/agent/diff-view.ts', mode: '100644', type: 'blob', sha: 'rc14', size: 743 },
      { path: 'modes/agent/orchestrator.ts', mode: '100644', type: 'blob', sha: 'rc15', size: 3428 },
      { path: 'modes/agent/tool-executor.ts', mode: '100644', type: 'blob', sha: 'rc16', size: 14916 },
      { path: 'modes/agent/types.ts', mode: '100644', type: 'blob', sha: 'rc17', size: 1542 },
      { path: 'modes/ask', mode: '040000', type: 'tree', sha: 'rc18' },
      { path: 'modes/ask/orchestrator.ts', mode: '100644', type: 'blob', sha: 'rc19', size: 6086 },
      { path: 'modes/plan', mode: '040000', type: 'tree', sha: 'rc20' },
      { path: 'modes/plan/orchestrator.ts', mode: '100644', type: 'blob', sha: 'rc21', size: 4438 },
      { path: 'modes/plan/planner.ts', mode: '100644', type: 'blob', sha: 'rc22', size: 5530 },
      { path: 'modes/plan/selection.ts', mode: '100644', type: 'blob', sha: 'rc23', size: 1482 },
      { path: 'modes/plan/types.ts', mode: '100644', type: 'blob', sha: 'rc24', size: 254 },
      { path: 'modes/plan/web-tools.ts', mode: '100644', type: 'blob', sha: 'rc25', size: 3681 },
      { path: 'modes/telegram', mode: '040000', type: 'tree', sha: 'rc26' },
      { path: 'modes/telegram/agent-run.ts', mode: '100644', type: 'blob', sha: 'rc27', size: 4686 },
      { path: 'modes/telegram/approval-session.ts', mode: '100644', type: 'blob', sha: 'rc28', size: 2975 },
      { path: 'modes/telegram/auth.ts', mode: '100644', type: 'blob', sha: 'rc29', size: 148 },
      { path: 'modes/telegram/constants.ts', mode: '100644', type: 'blob', sha: 'rc30', size: 264 },
      { path: 'modes/telegram/handlers.ts', mode: '100644', type: 'blob', sha: 'rc31', size: 6940 },
      { path: 'modes/telegram/index.ts', mode: '100644', type: 'blob', sha: 'rc32', size: 1444 },
      { path: 'modes/telegram/plan-session.ts', mode: '100644', type: 'blob', sha: 'rc33', size: 1597 },
      { path: 'modes/telegram/text.ts', mode: '100644', type: 'blob', sha: 'rc34', size: 750 },
      { path: 'tui', mode: '040000', type: 'tree', sha: 'rc35' },
      { path: 'tui/terminal-md.ts', mode: '100644', type: 'blob', sha: 'rc36', size: 498 },
      { path: 'tui/wakeup.ts', mode: '100644', type: 'blob', sha: 'rc37', size: 1682 },
    ],
  },

  'coderamp-labs/gitingest': {
    metadata: {
      owner: 'coderamp-labs',
      name: 'gitingest',
      fullName: 'coderamp-labs/gitingest',
      description: 'Turn any Git repository into a prompt-friendly text ingest for LLMs.',
      stars: 18400,
      forks: 1420,
      openIssues: 42,
      defaultBranch: 'main',
      language: 'Python',
      license: 'MIT',
      topics: ['llm', 'git', 'prompt-engineering', 'context-window', 'fastapi'],
      htmlUrl: 'https://github.com/coderamp-labs/gitingest',
      updatedAt: '2026-03-28T14:20:00Z',
      sizeKb: 3820,
    },
    readme: `# Gitingest\n\nTurn any Git repository into a prompt-friendly text ingest for LLMs.\n\n## Features\n- Easy code context: Get a text digest from a Git repository URL or a directory\n- Smart Formatting: Optimized output format for LLM prompts\n- Statistics about file/dir structure, size, and token counts\n- CLI tool & Python package\n\n## Usage\nReplace "hub" with "ingest" in any GitHub URL to access the corresponding digest.`,
    sampleFiles: {
      'src/gitingest/entrypoint.py': 'async def ingest_async(source: str, max_file_size: int = 10_000_000, include_patterns = None, exclude_patterns = None):\n    # Clone and analyze repo\n    pass',
      'src/gitingest/query_parser.py': 'async def parse_remote_repo(source: str, token: str | None = None) -> IngestionQuery:\n    # Normalizes GitHub URL, extracts branch and subpath\n    pass',
      'src/server/main.py': 'from fastapi import FastAPI\napp = FastAPI(title="Gitingest")\n@app.get("/{user}/{repo}")\nasync def ingest_page(user: str, repo: str):\n    return templates.TemplateResponse("git.jinja")',
    },
    tree: [
      { path: 'src', mode: '040000', type: 'tree', sha: 't1' },
      { path: 'src/gitingest', mode: '040000', type: 'tree', sha: 't2' },
      { path: 'src/gitingest/__init__.py', mode: '100644', type: 'blob', sha: 'b1', size: 167 },
      { path: 'src/gitingest/entrypoint.py', mode: '100644', type: 'blob', sha: 'b2', size: 13418 },
      { path: 'src/gitingest/ingestion.py', mode: '100644', type: 'blob', sha: 'b3', size: 11114 },
      { path: 'src/gitingest/clone.py', mode: '100644', type: 'blob', sha: 'b4', size: 6409 },
      { path: 'src/gitingest/query_parser.py', mode: '100644', type: 'blob', sha: 'b5', size: 6354 },
      { path: 'src/gitingest/output_formatter.py', mode: '100644', type: 'blob', sha: 'b6', size: 7141 },
      { path: 'src/server', mode: '040000', type: 'tree', sha: 't3' },
      { path: 'src/server/main.py', mode: '100644', type: 'blob', sha: 'b7', size: 7626 },
      { path: 'src/server/query_processor.py', mode: '100644', type: 'blob', sha: 'b8', size: 14821 },
      { path: 'src/server/templates', mode: '040000', type: 'tree', sha: 't4' },
      { path: 'src/server/templates/base.jinja', mode: '100644', type: 'blob', sha: 'b9', size: 3462 },
      { path: 'src/server/templates/components/git_form.jinja', mode: '100644', type: 'blob', sha: 'b10', size: 12473 },
      { path: 'src/server/templates/components/result.jinja', mode: '100644', type: 'blob', sha: 'b11', size: 8241 },
      { path: 'README.md', mode: '100644', type: 'blob', sha: 'b12', size: 14882 },
      { path: 'pyproject.toml', mode: '100644', type: 'blob', sha: 'b13', size: 3705 },
      { path: 'Dockerfile', mode: '100644', type: 'blob', sha: 'b14', size: 1528 },
    ],
  },
  'ahmedkhaleel2004/gitdiagram': {
    metadata: {
      owner: 'ahmedkhaleel2004',
      name: 'gitdiagram',
      fullName: 'ahmedkhaleel2004/gitdiagram',
      description: 'Turn any GitHub repository into an interactive architecture diagram or narrated video.',
      stars: 12800,
      forks: 980,
      openIssues: 28,
      defaultBranch: 'main',
      language: 'TypeScript',
      license: 'MIT',
      topics: ['nextjs', 'mermaid', 'diagram', 'architecture', 'ai-agent', 'mcp'],
      htmlUrl: 'https://github.com/ahmedkhaleel2004/gitdiagram',
      updatedAt: '2026-04-01T11:00:00Z',
      sizeKb: 5200,
    },
    readme: `# GitDiagram\n\nVisualize any codebase: turn any public or private GitHub repository into an interactive architecture diagram, or watch it explained in a one-minute narrated video.\n\nReplace "hub" with "diagram" in any GitHub repository URL.`,
    sampleFiles: {
      'src/server/generate/graph.ts': 'export function planArchitectureGraph(context: RepoContext): GraphSchema {\n  // Extracts subsystems, nodes, edges, and produces Mermaid flowchart\n}',
      'src/features/diagram/mermaid-config.ts': 'export const MERMAID_THEME = { theme: "neutral", flowchart: { curve: "basis" } };',
      'src/app/page.tsx': 'export default function HomePage() { return <MainCard /> }',
    },
    tree: [
      { path: 'src', mode: '040000', type: 'tree', sha: 't1' },
      { path: 'src/app', mode: '040000', type: 'tree', sha: 't2' },
      { path: 'src/app/page.tsx', mode: '100644', type: 'blob', sha: 'b1', size: 5254 },
      { path: 'src/app/[username]/[repo]/page.tsx', mode: '100644', type: 'blob', sha: 'b2', size: 4890 },
      { path: 'src/components', mode: '040000', type: 'tree', sha: 't3' },
      { path: 'src/components/main-card.tsx', mode: '100644', type: 'blob', sha: 'b3', size: 7269 },
      { path: 'src/components/hero.tsx', mode: '100644', type: 'blob', sha: 'b4', size: 3120 },
      { path: 'src/features', mode: '040000', type: 'tree', sha: 't4' },
      { path: 'src/features/diagram/api.ts', mode: '100644', type: 'blob', sha: 'b5', size: 5278 },
      { path: 'src/features/diagram/mermaid-config.ts', mode: '100644', type: 'blob', sha: 'b6', size: 2664 },
      { path: 'src/features/diagram/graph.ts', mode: '100644', type: 'blob', sha: 'b7', size: 4928 },
      { path: 'src/server', mode: '040000', type: 'tree', sha: 't5' },
      { path: 'src/server/generate/graph.ts', mode: '100644', type: 'blob', sha: 'b8', size: 15274 },
      { path: 'src/server/generate/prompts.ts', mode: '100644', type: 'blob', sha: 'b9', size: 13625 },
      { path: 'src/server/generate/mermaid-validator.ts', mode: '100644', type: 'blob', sha: 'b10', size: 9242 },
      { path: 'README.md', mode: '100644', type: 'blob', sha: 'b11', size: 5983 },
      { path: 'package.json', mode: '100644', type: 'blob', sha: 'b12', size: 5141 },
    ],
  },
  'reverse-codes/gitreverse': {
    metadata: {
      owner: 'reverse-codes',
      name: 'gitreverse',
      fullName: 'reverse-codes/gitreverse',
      description: 'Reverse engineer any GitHub repository or website into a plain-language coding agent prompt.',
      stars: 4850,
      forks: 310,
      openIssues: 12,
      defaultBranch: 'main',
      language: 'TypeScript',
      license: 'MIT',
      topics: ['cursor', 'claude-code', 'vibe-coding', 'prompt-engineering', 'nextjs'],
      htmlUrl: 'https://github.com/reverse-codes/gitreverse',
      updatedAt: '2026-03-15T09:30:00Z',
      sizeKb: 2100,
    },
    readme: `# GitReverse\n\nTurn a public GitHub repository into a single synthetic user prompt that someone might paste into Cursor, Claude Code, Codex, etc. to vibe code the project from scratch.\n\nThe app pulls repo metadata, a root file tree, and the README, then uses an LLM to produce one short, conversational prompt.`,
    sampleFiles: {
      'lib/system-prompt.ts': 'export const SYSTEM_PROMPT = `You are an expert at inferring how people actually prompt modern coding agents...`;',
      'app/api/reverse-prompt/route.ts': 'export async function POST(req: NextRequest) { /* generate synthetic prompt */ }',
    },
    tree: [
      { path: 'app', mode: '040000', type: 'tree', sha: 't1' },
      { path: 'app/page.tsx', mode: '100644', type: 'blob', sha: 'b1', size: 1373 },
      { path: 'app/globals.css', mode: '100644', type: 'blob', sha: 'b2', size: 492 },
      { path: 'app/api/reverse-prompt/route.ts', mode: '100644', type: 'blob', sha: 'b3', size: 17516 },
      { path: 'components', mode: '040000', type: 'tree', sha: 't2' },
      { path: 'components/reverse-prompt-home.tsx', mode: '100644', type: 'blob', sha: 'b4', size: 25329 },
      { path: 'components/navbar.tsx', mode: '100644', type: 'blob', sha: 'b5', size: 3410 },
      { path: 'lib', mode: '040000', type: 'tree', sha: 't3' },
      { path: 'lib/system-prompt.ts', mode: '100644', type: 'blob', sha: 'b6', size: 2281 },
      { path: 'lib/github-client.ts', mode: '100644', type: 'blob', sha: 'b7', size: 4120 },
      { path: 'lib/file-tree-formatter.ts', mode: '100644', type: 'blob', sha: 'b8', size: 3200 },
      { path: 'README.md', mode: '100644', type: 'blob', sha: 'b9', size: 4081 },
      { path: 'package.json', mode: '100644', type: 'blob', sha: 'b10', size: 936 },
    ],
  },
  'fastapi/fastapi': {
    metadata: {
      owner: 'fastapi',
      name: 'fastapi',
      fullName: 'fastapi/fastapi',
      description: 'FastAPI framework, high performance, easy to learn, fast to code, ready for production',
      stars: 82000,
      forks: 7100,
      openIssues: 195,
      defaultBranch: 'master',
      language: 'Python',
      license: 'MIT',
      topics: ['python', 'asgi', 'openapi', 'pydantic', 'async', 'api'],
      htmlUrl: 'https://github.com/fastapi/fastapi',
      updatedAt: '2026-04-02T18:00:00Z',
      sizeKb: 14500,
    },
    readme: `# FastAPI\n\nFastAPI is a modern, fast (high-performance), web framework for building APIs with Python based on standard Python type hints.\n\nKey features: Fast to code, Fewer bugs, Intuitive, Easy, Short, Robust, Standards-based.`,
    sampleFiles: {
      'fastapi/applications.py': 'class FastAPI(Starlette):\n    def __init__(self, debug: bool = False, routes: list = None):\n        super().__init__()',
      'fastapi/routing.py': 'class APIRoute(routing.Route):\n    def __init__(self, path: str, endpoint: Callable):\n        pass',
    },
    tree: [
      { path: 'fastapi', mode: '040000', type: 'tree', sha: 't1' },
      { path: 'fastapi/applications.py', mode: '100644', type: 'blob', sha: 'b1', size: 21300 },
      { path: 'fastapi/routing.py', mode: '100644', type: 'blob', sha: 'b2', size: 31200 },
      { path: 'fastapi/params.py', mode: '100644', type: 'blob', sha: 'b3', size: 14500 },
      { path: 'fastapi/dependencies/utils.py', mode: '100644', type: 'blob', sha: 'b4', size: 18200 },
      { path: 'fastapi/openapi/utils.py', mode: '100644', type: 'blob', sha: 'b5', size: 19800 },
      { path: 'fastapi/encoders.py', mode: '100644', type: 'blob', sha: 'b6', size: 8400 },
      { path: 'fastapi/exceptions.py', mode: '100644', type: 'blob', sha: 'b7', size: 4500 },
      { path: 'README.md', mode: '100644', type: 'blob', sha: 'b8', size: 22000 },
      { path: 'pyproject.toml', mode: '100644', type: 'blob', sha: 'b9', size: 5400 },
    ],
  },
  'shadcn-ui/ui': {
    metadata: {
      owner: 'shadcn-ui',
      name: 'ui',
      fullName: 'shadcn-ui/ui',
      description: 'Beautifully designed components that you can copy and paste into your apps. Accessible. Customizable. Open Source.',
      stars: 84500,
      forks: 6400,
      openIssues: 120,
      defaultBranch: 'main',
      language: 'TypeScript',
      license: 'MIT',
      topics: ['react', 'tailwindcss', 'radix-ui', 'components', 'ui'],
      htmlUrl: 'https://github.com/shadcn-ui/ui',
      updatedAt: '2026-04-03T16:20:00Z',
      sizeKb: 18200,
    },
    readme: `# shadcn/ui\n\nAccessible and customizable components that you can copy and paste into your apps. Free. Open Source. Use this to build your own component library.`,
    sampleFiles: {
      'packages/cli/src/index.ts': '#!/usr/bin/env node\nimport { Command } from "commander";',
      'apps/www/components/ui/button.tsx': 'export const Button = React.forwardRef(...)',
    },
    tree: [
      { path: 'packages', mode: '040000', type: 'tree', sha: 't1' },
      { path: 'packages/cli/src/index.ts', mode: '100644', type: 'blob', sha: 'b1', size: 5200 },
      { path: 'packages/cli/src/commands/add.ts', mode: '100644', type: 'blob', sha: 'b2', size: 8400 },
      { path: 'packages/cli/src/commands/init.ts', mode: '100644', type: 'blob', sha: 'b3', size: 9100 },
      { path: 'apps/www/components/ui/button.tsx', mode: '100644', type: 'blob', sha: 'b4', size: 3100 },
      { path: 'apps/www/components/ui/dialog.tsx', mode: '100644', type: 'blob', sha: 'b5', size: 4500 },
      { path: 'README.md', mode: '100644', type: 'blob', sha: 'b6', size: 12000 },
      { path: 'package.json', mode: '100644', type: 'blob', sha: 'b7', size: 3100 },
    ],
  },
};
