/**
 * Diagram Export utilities ported from GitDiagram
 * Supports high-resolution 4x canvas PNG export, SVG download, and README Markdown generation.
 */

const PNG_EXPORT_SCALE = 4;
const MAX_PNG_EXPORT_DIMENSION = 16_000;
const MAX_PNG_EXPORT_PIXELS = 120_000_000;
const SVG_NS = 'http://www.w3.org/2000/svg';

function loadSvgImage(sourceUrl: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const image = new Image();
    image.onload = () => resolve(image);
    image.onerror = () => reject(new Error('Unable to decode diagram SVG.'));
    image.src = sourceUrl;
  });
}

function encodeCanvasAsPng(canvas: HTMLCanvasElement): Promise<Blob> {
  return new Promise((resolve, reject) => {
    canvas.toBlob((blob) => {
      if (blob) {
        resolve(blob);
      } else {
        reject(new Error('Unable to encode diagram PNG.'));
      }
    }, 'image/png');
  });
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.download = filename;
  anchor.href = url;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}

export function downloadSvg(svgHtml: string, filename = 'diagram.svg'): void {
  const blob = new Blob([svgHtml], { type: 'image/svg+xml;charset=utf-8' });
  downloadBlob(blob, filename);
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (err) {
    console.error('Clipboard copy failed:', err);
    return false;
  }
}

function standaloneSvg(
  svgElement: SVGSVGElement,
  width: number,
  height: number,
  scale: number
) {
  const clone = svgElement.cloneNode(true) as SVGSVGElement;
  for (const property of ['width', 'height', 'max-width', 'transform']) {
    clone.style.removeProperty(property);
  }
  if (!clone.getAttribute('viewBox')) {
    clone.setAttribute('viewBox', `0 0 ${width} ${height}`);
  }
  clone.setAttribute('xmlns', SVG_NS);
  clone.setAttribute('width', String(Math.ceil(width * scale)));
  clone.setAttribute('height', String(Math.ceil(height * scale)));
  return new XMLSerializer().serializeToString(clone);
}

export async function exportMermaidSvgAsPng(
  svgElement: SVGSVGElement,
  isDark = true,
  repository = 'repository'
): Promise<void> {
  const bbox = svgElement.getBBox();
  const viewBox = svgElement.viewBox.baseVal;
  const width = viewBox?.width > 0 ? viewBox.width : bbox.width;
  const height = viewBox?.height > 0 ? viewBox.height : bbox.height;

  if (width <= 0 || height <= 0) {
    throw new Error('Diagram has no exportable dimensions.');
  }

  const scale = Math.min(
    PNG_EXPORT_SCALE,
    MAX_PNG_EXPORT_DIMENSION / width,
    MAX_PNG_EXPORT_DIMENSION / height,
    Math.sqrt(MAX_PNG_EXPORT_PIXELS / (width * height))
  );

  const backgroundColor = isDark ? '#070512' : '#ffffff';
  const footerHeight = 44;
  const footerText = `Gitometer • CodeMap: ${repository}`;

  const svgBlob = new Blob([standaloneSvg(svgElement, width, height, scale)], {
    type: 'image/svg+xml;charset=utf-8',
  });
  const svgUrl = URL.createObjectURL(svgBlob);

  try {
    const image = await loadSvgImage(svgUrl);
    const canvas = document.createElement('canvas');
    canvas.width = Math.max(1, Math.floor(width * scale));
    canvas.height = Math.max(1, Math.floor((height + footerHeight) * scale));

    const context = canvas.getContext('2d');
    if (!context) {
      throw new Error('Unable to create image export canvas.');
    }

    context.fillStyle = backgroundColor;
    context.fillRect(0, 0, canvas.width, canvas.height);

    context.scale(scale, scale);
    context.drawImage(image, 0, 0, width, height);

    context.fillStyle = isDark ? 'rgba(255, 255, 255, 0.65)' : 'rgba(0, 0, 0, 0.65)';
    context.font = '600 13px ui-sans-serif, system-ui, -apple-system, sans-serif';
    context.textAlign = 'right';
    context.textBaseline = 'middle';
    context.fillText(footerText, width - 16, height + footerHeight / 2);

    const blob = await encodeCanvasAsPng(canvas);
    downloadBlob(blob, `${repository.replace(/[/\\?%*:|"<>]/g, '_')}_architecture.png`);
  } finally {
    URL.revokeObjectURL(svgUrl);
  }
}

export function getReadmePictureMarkdown(repository: string): string {
  const parts = repository.split('/');
  const owner = parts[0] || 'owner';
  const repo = parts[1] || 'repo';
  return `<!-- Architecture Diagram generated by Gitometer CodeMap (GitDiagram Engine) -->\n[![Architecture Diagram](https://img.shields.io/badge/Architecture-Interactive%20CodeMap-7c3aed?style=for-the-badge&logo=git&logoColor=white)](https://github.com/${owner}/${repo})\n`;
}

export function getReadmeBadgeMarkdown(repository: string): string {
  const parts = repository.split('/');
  const owner = parts[0] || 'owner';
  const repo = parts[1] || 'repo';
  return `[![CodeMap Architecture](https://img.shields.io/badge/CodeMap-Architecture-9333ea?logo=mermaid&style=flat-square)](https://github.com/${owner}/${repo})`;
}
